@startuml
allow_mixing

frame ROS{
webcam : camera video
camera_node : Despliegue de imagen
greendetector : Detección
greendetector : Contorno
greendetector : Coordenadas
coordinate_multiplier : Librería (so)
coordinate_multiplier : Multiplica la coordenada
}
wrapper : Convierte ROS Topic en gRPC
appJava : server que recibe coordenadas
terminal : imprime
go_gateway : GRPC gateway
postman : Postman 

webcam --> camera_node : Despliegue de imagen
webcam --> greendetector : ROS node Real Time Img
coordinate_multiplier -> greendetector

greendetector --> wrapper : ROS Topic (/green_object_coordinates)
wrapper --> greendetector
wrapper -> appJava
appJava --> terminal

wrapper-->go_gateway
go_gateway-->wrapper

postman->go_gateway
go_gateway->postman

@enduml