# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import cx100_pb2 as cx100__pb2


class GreenObjectServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.PublishObjectCoordinates = channel.unary_unary(
        '/object_detection.GreenObjectService/PublishObjectCoordinates',
        request_serializer=cx100__pb2.Empty.SerializeToString,
        response_deserializer=cx100__pb2.ObjectCoordinates.FromString,
        )


class GreenObjectServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def PublishObjectCoordinates(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GreenObjectServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'PublishObjectCoordinates': grpc.unary_unary_rpc_method_handler(
          servicer.PublishObjectCoordinates,
          request_deserializer=cx100__pb2.Empty.FromString,
          response_serializer=cx100__pb2.ObjectCoordinates.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'object_detection.GreenObjectService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
